### ISSUE TITLE
Redmine 1.4.0 

### ISSUE THREAD

**Issue by RcRaCk2k** [chantra/redmine_newissuealerts#19]
Running Redmine 1.4.0. Got this error:

```
ActionView::TemplateError (undefined method `errors' for :newissuealert:Symbol) on line #3 of vendor/plugins/chantra-redmine_newissuealerts-d2fe17e/app/views/newissuealerts/new.html.erb:
1: <h2><%= l(:newissuealerts_new, :project => @project.name) %></h2>
2: <% form_for :newissuealert, @newissuealert, :url => { :project_id => @project.identifier } do |f| %>
3:   <%= f.error_messages %>
4: <div class="box tabular settings">
5:   <p>
6:     <%= f.label l(:email_addresses) %> <%= f.text_field :mail_addresses %>

    app/helpers/application_helper.rb:954:in `block in error_messages_for'
    app/helpers/application_helper.rb:954:in `map'
    app/helpers/application_helper.rb:954:in `error_messages_for'
    vendor/plugins/chantra-redmine_newissuealerts-d2fe17e/app/views/newissuealerts/new.html.erb:3:in `block in _run_erb_vendor47plugins47chantra45redmine_newissuealerts45d2fe17e47app47views47newissuealerts47new46html46erb'
    vendor/plugins/chantra-redmine_newissuealerts-d2fe17e/app/views/newissuealerts/new.html.erb:2
    <internal:prelude>:10:in `synchronize'
    public/dispatch.fcgi:24:in `<main>'

Rendering /vhosts/redmine/public/500.html (500 Internal Server Error)
```

**Comment by RcRaCk2k** [comment]
If you comment out line 3, then the error disappears.

**Comment by anthonygerrard** [comment]
The plugin doesn't seem to work after upgrading to 1.4.5.

We get the following error when raising an issue

```
ActionView::MissingTemplate (Missing template newissuealerts_mailer/newissuealert.text.erb in view path vendor/plugins/chantra-redmine_newissuealerts-d2fe17e/app/views:vendor/plugins/giddie-redmine_default_assign-fbfe1c0/app/views:app/views):
  app/models/mailer.rb:454:in `render_multipart'
  app/controllers/issues_controller.rb:148:in `create'
  config/initializers/mongrel.rb:74:in `dispatch_cgi'
```

and the following if you try to delete an alert

```
ActionView::TemplateError (undefined method `errors' for :newissuealert:Symbol) on line #3 of vendor/plugins/chantra-redmine_newissuealerts-d2fe17e/app/views/newissuealerts/edit.html.erb:
1: <h2><%= l(:newissuealerts_edit, :project => @project.name) %></h2>
2: <% form_for :newissuealert, @newissuealert , :url => { :project_id => @project.identifier, :id => @newissuealert.id }do |f| %>
3:   <%= f.error_messages %>
4: <div class="box tabular settings">
5:   <p>
6:     <%= f.label l(:email_addresses) %> <%= f.text_field :mail_addresses, :size => 60 %><br />

    app/helpers/application_helper.rb:956:in `error_messages_for'
    app/helpers/application_helper.rb:956:in `map'
    app/helpers/application_helper.rb:956:in `error_messages_for'
    vendor/plugins/chantra-redmine_newissuealerts-d2fe17e/app/views/newissuealerts/edit.html.erb:3
    vendor/plugins/chantra-redmine_newissuealerts-d2fe17e/app/views/newissuealerts/edit.html.erb:2
    config/initializers/mongrel.rb:74:in `dispatch_cgi'
```
